// NfdHighlighter.idl : IDL source for NfdHighlighter
//

// This file will be processed by the MIDL tool to
// produce the type library (NfdHighlighter.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(B20E32BF-D4A3-4531-9030-E13D2B6A642A),
	dual,
	nonextensible,
	helpstring("IMyOverlayIcon Interface"),
	pointer_default(unique)
]
interface IMyOverlayIcon : IDispatch{
};
[
	uuid(8F8AE675-182D-4F64-B501-D92264C57598),
	version(1.0),
	helpstring("NfdHighlighter 1.0 Type Library")
]
library NfdHighlighterLib
{
	importlib("stdole2.tlb");
	[
		uuid(FDCA2A20-D464-4FAE-AF1A-0924DF298D0F),
		helpstring("MyOverlayIcon Class")
	]
	coclass MyOverlayIcon
	{
		[default] interface IMyOverlayIcon;
	};
};
